project:
  type: website
  render:
    - index.qmd
    - analysis/*.qmd
    - presentations/*.qmd
  output-dir: docs

website:
  title: "Riversea Project"
  navbar: 
    left: 
      - text: Analysis
        href: index.qmd
      - text: Presentations
        href: presentations/index.qmd

format:
  html:
    toc: true
    theme: cosmo
