project:
  type: website
  render:
    - index.qmd
    - analysis/*.qmd
    - presentations/*.qmd
    - output/*.qmd
  output-dir: docs

website:
  title: "RIVERSEA"
  navbar:
    background: primary
    foreground: light
    left:
      - text: Home
        href: index.qmd
      - text: Lab notebooks
        href: analysis/index.qmd
      - text: Presentations
        href: presentations/index.qmd
      - text: Manuscript
        href: output/manuscript.qmd
      - text: Reports
        href: output/index.qmd

format:
  html:
    toc: true
    theme: [cosmo, brand]
