project:
  type: website
  render:
    - index.qmd
    - analysis/*.qmd
  output-dir: docs

website:
  title: "Riversea Project Reports"
  navbar: 
    left: 
      - text: Home
        href: index.qmd

format:
  html:
    toc: true
    theme: cosmo
