---
title: "Define the statistical model"
format: html
execute:
    message: false
    warning: false
---

# Summary

This notebook contains

- the reasonning underlying the model definition that we intend to use in our study
- the list of causal relationships that we assume, illustrated with a DAG
- ecological interpretations relating these causal relationships to ecological processes.

# 1. Write the DAG

First, let's think about the causal relationship between our covariables and the metric we want to predict, that is, food web structure.
For now, we will forget about details of how to capture best dam impact with summary metrics.
Instead, we focus here on the overall causal relationships among our variables.
Directed Acyclic Graph are a common and graphical way to write the causal relationships assumed between the set of variables of interest.

# 2. Capture dam impacts

Next, let's focus on how to best capture dam impact.
We begin with an illustration of how dams can impact a given community at a local scale in @fig-dam.

![Sketch of upstream and downstream dam impacts on a given community. The impact of a upstream dam reflects the decrease of migration (upstream-downstream), and other hydrographic effects of dams such as reduction of flow and sedimentation. The impact of downstream dam reflects the decrease of migration (downstream-upstream), and the transition from lotic to lentic environment.](sketch-dam-impact.png){#fig-dam}
