---
title: "Build food webs"
format: 
  html:
    embed-resources: true
execute:
    message: false
    warning: false
---

## Summary

```{r}
#| output: false
library(renv)
renv::load()
renv::restore() # Install missing librairies.
renv::status() # Check the project state.

library(targets)
library(here)
tar_config_set(
  store = here::here("_targets")
)
library(foodwebbuilder)
library(dplyr)
```

Individual fish size.

```{r}
d_size <- tar_read(sea_data_imputed)$size
d_size <- d_size |> rename(species_code = species_valid, size = length)
head(d_size)
```

Diet.

```{r}
d_diet <- read.csv(here(tar_read(diet_file)))
d_diet <- d_diet |>
  rename(
    species_code = species,
    size_min = length_min,
    size_max = length_max,
  )
head(d_diet)
```

Predation window.

```{r}
predation_window <- tar_read(predation_window)
predation_window <- predation_window |> rename(species_code = species)
head(predation_window)
```

First, we remove species with incomplete information.

```{r}
d_size_clean <- remove_missing_species(
  ind_measure = d_size,
  fish_diet_shift = d_diet,
  pred_win = predation_window
)
```

Then, we define size classes for all species.

```{r}
size_classes <- compute_size_classes(
  ind_measure = d_size_clean,
  num_classes = 5
)
head(size_classes)
```

Next, we build the metaweb.
Before that we need to load the diet table for the resources.

```{r}
d_resource <- read.csv(here("data", "diet", "resource_diet_shift.csv"))
d_resource <- d_resource |>
  mutate(species = if_else(
    species == "biofilms",
    "biofilm",
    species
  ))
d_resource$species_code <- d_resource$species
d_resource <- d_resource |> rename(
  detritus = det,
  biofilm = biof,
  macrophyte = macroph,
  phytoplankton = phytopl,
  zooplankton = zoopl,
  zoobenthos = zoob
)
head(d_resource)
```

```{r}
resources <- c(
  "zooplankton",
  "phytoplankton",
  "biofilm",
  "zoobenthos",
  "macrophyte",
  "detritus"
)
metaweb <- build_metaweb(
  tab_size_classes = size_classes,
  pred_win = predation_window,
  fish_diet_shift = d_diet,
  resource_diet_shift = d_resource,
  num_classes = 5,
  selected_resources = resources
)
```



