utils::globalVariables(c(
  "abundance", "abundance_cor", "Age", "Annee", "AnaCat", "batch_size",
  "brack", "Brack", "C_VALIDE",
  "Campagne", "category", "CdEuMasseD", "code", "CommonessII",
  "connectance", "Coord_Deb_xmin", "Coord_Deb_ymin", "Coord_Fin_xmin",
  "Coord_Fin_ymin", "country", "date_operation", "DemersPelag", "dist_km",
  "demers_pelag", "dist_to_district",
  "district", "eat", "ELEVATION_IGN25M", "environment", "Espece",
  "estimate", "fish",
  "FoodI", "FoodII", "FoodIII", "fresh", "Fresh", "frac_piscivorous",
  "from", "from_label",
  "geometry", "has_larvae", "id", "ID_interne_prelevement", "IS_FISH",
  "is_valid", "juvenile_length_max", "L_VALIDE", "L50", "label", "Lat",
  "latitude", "length_max", "length_min", "lg0_max", "LG0max", "light",
  "Lm", "log_species_richness", "log_trophic_richness", "Long",
  "longitude", "Longueur", "Longueur_fourche_mm", "Maturite",
  "maturity_length.x", "maturity_length.y", "measured", "metaweb",
  "method", "migratory_category", "Mois", "mu", "n_measured", "n_missing",
  "n_obs", "name",
  "native_status", "nearest_idx", "Nind_esp", "Nind_esp_taille", "node",
  "node_id", "Nombre",
  "NomScient", "num_classes", "observable", "occurence", "operation_id",
  "others", "p", "P.Value", "parameter_code", "path1", "path2", "Poids",
  "PredatorStage", "Predictor", "prey", "prey_category", "quality",
  "reference", "response", "Response", "saltwater", "Saltwater",
  "sandre_code", "scientific_name",
  "Sexe", "share", "sigma", "significant", "site_id", "size_max",
  "size_min", "species", "Species", "species_code", "species_valid",
  "Status", "stage", "Std.Estimate", "survey", "text", "threshold", "to",
  "to_plot",
  "total", "trait", "Trait", "trophic_length", "unit", "value",
  "variable", "with_juvenile", "x_end", "x_start", "y_end", "y_start",
  "year", "zone_id", "depth", "level"
))
